# -*- coding: utf-8 -*-
"""Telefone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvB85W3A5QLc3q_2EW1N3fAzKR9ABC6L
"""

hora_inicio = int(input("Digite a hora de inicio: "))
minuto_inicio = int(input("Digite o minuto de inicio: "))
valor_minuto = 5

hora_fim = int(input("Digite a hora de fim: "))
minuto_fim = int(input("Digite o minuto de fim: "))

final = hora_fim*60 + minuto_fim
inicio = hora_inicio*60 + minuto_inicio

diferenca_em_minutos = final - inicio

print(f"A ligação durou: {diferenca_em_minutos}")

desconto = 0
if (hora_inicio >0 and hora_inicio <=9):
  if (hora_fim >=0 and hora_fim <=9):
    dif = final - inicio
    print("Minutos com descontos",dif)
    print("Valor cobrado:", dif * valor_minuto * 0.5)
  else:
    normal = final - 9 * 60
    desc = 9*60 - inicio
    print("Minutos com desconto", desc)
    valor_desc = desc * (valor_minuto * 0.5)
    print("Valor sem desconto", normal)
    print("Total da ligação", normal + valor_desc)

if (hora_inicio >9 and hora_inicio <=18):
  if (hora_fim >=9 and hora_fim <=18):
    dif = final - inicio
    print("Minutos com descontos",dif)
    print("Valor cobrado:", dif * valor_minuto * 0.5)
  else:
    normal = final - 18 * 60
    desc = 18*60 - inicio
    print("Minutos com desconto", desc)
    valor_desc = desc * (valor_minuto * 0.5)
    print("Valor sem desconto", normal)
    print("Total da ligação", normal + valor_desc)

if (hora_inicio >18 and hora_inicio <=21):
  if (hora_fim >=18 and hora_fim <=21):
    dif = final - inicio
    print("Minutos com descontos",dif)
    print("Valor cobrado:", dif * valor_minuto * 0.5)
  else:
    normal = final - 21 * 60
    desc = 21*60 - inicio
    print("Minutos com desconto", desc)
    valor_desc = desc * (valor_minuto * 0.5)
    print("Valor sem desconto", normal)
    print("Total da ligação", normal + valor_desc)

if (hora_inicio > 21 and hora_inicio <=23):
  if (hora_fim >= 21 and hora_fim <=23):
    dif = final - inicio
    print("Minutos com descontos",dif)
    print("Valor cobrado:", dif * valor_minuto * 0.5)
  else:
    normal = final - 23 * 60
    desc = 23*60 - inicio
    print("Minutos com desconto", desc)
    valor_desc = desc * (valor_minuto * 0.5)
    print("Valor sem desconto", normal)
    print("Total da ligação", normal + valor_desc)